main:
  - identifier: about
    name: ğŸ’›About
    url: about
    weight: 1
  - identifier: archive
    name: ğŸ—„ï¸Archive
    url: archive
    weight: 2
    # Keep this for later
  # - identifier: presentation
  #   name: Pt
  #   url: presentation
  #   weight: 3
  - identifier: gallery
    name: ğŸ–¼ï¸Gallery
    url: gallery
    weight: 4
  - parent: gallery
    name: Riccardo family
    url: gallery/family
  - parent: gallery
    name: Riccardo sport
    url: gallery/riccardosport
  - parent: gallery
    name: Riccardo at-once
    url: gallery/riccardo-at-once
  - parent: gallery
    name: Photo
    url: gallery/photo
  - identifier: posts
    name: ğŸ“ªPosts
    url: posts
    weight: 5

  - identifier: ricc_zzo_prod
    name: ğŸŒBlog
    url: https://ricc-zzo.netlify.app/en/
    weight: 10



    # [Riccardo] This is AMAZING but still nothing to show.
  # - identifier: showcase
  #   name: Showcase
  #   url: showcase
  #   weight: 6

    # [Riccardo] This is AMAZING but still nothing to show.
  # - identifier: publication
  #   name: Pub
  #   url: publication
  #   weight: 7
