main:
  - identifier: about
    name: ğŸ’›Scopri altro
    url: about
    weight: 1
  - identifier: archive
    name: ğŸ—„ï¸Archivio
    url: archive
    weight: 2
  - identifier: gallery
    name: ğŸ–¼ï¸Foto
    url: gallery
    weight: 3
  # - parent: gallery
  #   name: fiverr
  #   url: gallery/mine
  - identifier: posts
    name:  ğŸ“ªArticoli
    url: posts
    weight: 4

  - identifier: ricc_zzo_prod
    name: ğŸŒBlog
    url: https://ricc-zzo.netlify.app/
    weight: 10
