main:
  - identifier: about
    name: ğŸ’›About
    url: about
    weight: 1
  - identifier: archive
    name: ğŸ—„ï¸Archive
    url: archive
    weight: 2
    # Keep this for later
  # - identifier: presentation
  #   name: Pt
  #   url: presentation
  #   weight: 3
  - identifier: gallery
    name: ğŸ–¼ï¸Gallery
    url: gallery
    weight: 4
  - parent: gallery
    name: My Family
    url: gallery/riccardo-family
  - parent: gallery
    name: Ricc sport
    url: gallery/riccardo-sport
  - parent: gallery
    name: Ricc Zibaldone
    url: gallery/riccardo-zibaldone
  - parent: gallery
    name: Ricc Work
    url: gallery/riccardo-work
    # My wife doesnt like this
  # - parent: gallery
  #   name: Photo
  #   url: gallery/photo
  - identifier: posts
    name: ğŸ“ªPosts
    url: posts
    weight: 5

  - identifier: ricc_zzo_prod
    name: ğŸŒBlog
    url: https://ricc-zzo.netlify.app/en/
    weight: 10



    # [Riccardo] This is AMAZING but still nothing to show.
  # - identifier: showcase
  #   name: Showcase
  #   url: showcase
  #   weight: 6

    # [Riccardo] This is AMAZING but still nothing to show.
  # - identifier: publication
  #   name: Pub
  #   url: publication
  #   weight: 7
