baseURL: 'http://ricc.rocks'
languageCode: 'en-us'
title: 'Ricc ğŸ’› Blog (Ananke)'
#theme = 'netlify-basic'
#theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]
theme: 'ananke'
background_color_class: "bg-yellow"
# example from https://gohugo.io/hugo-modules/use-modules/
# module:
#   imports:
#   - path: github.com/spf13/hyde
menu:
  main:
  - identifier: cats
    name: Categz
    url: /categories/
    weight: 10
  - identifier: posts
    name: Posts
    url: /posts/
    weight: 20
  - identifier: archives
    name: archives
    url: /archives/
    weight: 20

# doesnt work for Ananke I guess.. oh yes it does:
params:
  read_more_copy: Read more about this entry for Ananke
  description: "Your custom description for Hyde"
  themeColor: "theme-base-0a" # Hyde
  #commentoEnable: true
disqusShortname: disqus_7JS1PTrMOB

# Hyde
Menus:
  main:
    - Name: "ğŸ§‘ğŸ»â€ğŸ’»Github"
      URL: "https://github.com/palladius/"
    - Name: "ğŸ’¼ LinkedIn"
      URL: "https://www.linkedin.com/in/riccardocarlesso/ "
